### ISSUE TITLE
Travis intégration

### ISSUE THREAD

**Issue by gortium** [WalkingMachine/sara_robot#1]
Travis intégration

**Comment by gortium** [comment]
@maximest-pierre  svp x)

**Comment by maximest-pierre** [comment]
Tes chanceux que la nav fonctionne bien la. Je vais le faire toute suite.

**Comment by gortium** [comment]
Yeah Merci :)

**Comment by gortium** [comment]
@maximest-pierre L'intégration est fini? Si il reste juste le script travis.yaml, je peux le finir !

**Comment by maximest-pierre** [comment]
ses juste les script travis qui reste a faire pis aussi assurer que sa passe

**Comment by gortium** [comment]
Parfait merci !! :D

**Comment by gortium** [comment]
Mon app supporte juste un assignment sorry ^^
